#!/bin/bash

# utility for comparing commands between two different fin-cli versions.

if [ $# -lt 3 ]; then
	echo 'usage: <version-a> <version-b> <fin-path>'
	exit 1
fi

fin_path=$3

get_syn_list() {
	git checkout $1
	fin --path=$fin_path --cmd-dump | php $(dirname $0)/syn-list.php
}

get_syn_list $1 > /tmp/fin-cli-a
get_syn_list $2 > /tmp/fin-cli-b

diff /tmp/fin-cli-a /tmp/fin-cli-b > cmd.diff

echo 'Generated cmd.diff'
